[package]
name = "ober"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
colored = "2.0.0"
structopt = "0.3.25"
tokio = { version = "1", features = ["full"] }
warp = "0.3.2"
